package aoc2023

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class Day11Test : FunSpec({
  test("expand") {
    Day11().expand(
      """
      ...#......
      .......#..
      #.........
      ..........
      ......#...
      .#........
      .........#
      ..........
      .......#..
      #...#.....
    """.trimIndent()
    ).joinToString("\n") {
      it.joinToString(separator = "") {
        if (it) "#" else "."
      }
    }.shouldBe(
      """
        ....#........
        .........#...
        #............
        .............
        .............
        ........#....
        .#...........
        ............#
        .............
        .............
        .........#...
        #....#.......
      """.trimIndent()
    )
  }

  test("part1") {
    Day11().part1(
      """
        ...#......
        .......#..
        #.........
        ..........
        ......#...
        .#........
        .........#
        ..........
        .......#..
        #...#.....        
      """.trimIndent()
    ).shouldBe(
      374
    )
  }
})
